name: deploy to github pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v7
      - name: set build env
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          echo "PUBLIC_COMMIT_HASH=$SHORT_SHA" >> $GITHUB_ENV
          echo "PUBLIC_COMMIT_LINK=${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}" >> $GITHUB_ENV
      - name: build and upload the site
        uses: withastro/action@v6
        env:
          PUBLIC_COMMIT_HASH: ${{ env.PUBLIC_COMMIT_HASH }}
          PUBLIC_COMMIT_LINK: ${{ env.PUBLIC_COMMIT_LINK }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy pages
        id: deployment
        uses: actions/deploy-pages@v5
